# Generated by Django 5.1.5 on 2025-01-17 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=255)),
                ("roll_no", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="teacher_images/")),
                (
                    "class_10_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "class_12_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("degree_name", models.CharField(max_length=255)),
                (
                    "degree_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("opinion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TutorApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("class_of_study", models.CharField(max_length=50)),
                ("subjects", models.TextField()),
                ("num_children", models.PositiveIntegerField()),
                ("contact_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=100)),
                ("full_marks", models.IntegerField()),
                ("passing_marks", models.IntegerField()),
                ("obtained_marks", models.IntegerField()),
                (
                    "student_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="app.studentresult",
                    ),
                ),
            ],
        ),
    ]
