# Generated by Django 5.1.5 on 2025-01-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_studentresult_student"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subject",
            new_name="SubjectResult",
        ),
    ]
