# Generated by Django 5.1.5 on 2025-01-18 05:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_subject_subjectresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectresult",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
