# Generated by Django 5.1.5 on 2025-01-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorapplication",
            name="other_courses",
            field=models.TextField(
                blank=True,
                help_text="Specify other courses if any (optional)",
                null=True,
                verbose_name="Other Courses",
            ),
        ),
        migrations.AlterField(
            model_name="tutorapplication",
            name="class_of_study",
            field=models.CharField(
                blank=True,
                help_text="subject",
                max_length=50,
                null=True,
                verbose_name="Subject",
            ),
        ),
    ]
