# Generated by Django 5.1.5 on 2025-01-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_tutorapplication_other_courses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorapplication",
            name="class_of_study",
            field=models.CharField(default=0, max_length=50),
        ),
    ]
