# Generated by Django 5.1.5 on 2025-01-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_tutorapplication_class_of_study"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutorapplication",
            name="other_courses",
        ),
        migrations.AlterField(
            model_name="tutorapplication",
            name="class_of_study",
            field=models.CharField(max_length=50),
        ),
    ]
