# Generated by Django 5.1.5 on 2025-01-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_tutorapplication_other_courses_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="id",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="image",
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
